### ISSUE TITLE
when call driver.stop(), pymesos throws a RuntimeError. 

### ISSUE THREAD

**Issue by yuyang0** [douban/pymesos#8]
I just want to stop the scheduler, so I call `driver.stop()` , but pymesos throws an exception,  I'm a newbie to mesos, so I really can't figure out what's wrong, the following is the traceback:
    
    2015-09-07 09:52:57,059 - [process.py:72 -        run_jobs() ]: ERROR    error while call <function handle at 0x7f22dfdefd70> (tried 0 times)
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 69, in run_jobs
        func(*args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 138, in handle
    f(*args)
      File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 108, in onStatusUpdateMessage
    self.sched.statusUpdate(self, update.status)
      File "/home/yangyu/Documents/my-code/geetest/gt-mesos-framework/gmesos/scheduler.py", line 130, in statusUpdate
    driver.stop()
      File "/usr/local/lib/python2.7/dist-packages/pymesos/scheduler.py", line 155, in stop
    Process.stop(self)
      File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 146, in stop
    self.join()
      File "/usr/local/lib/python2.7/dist-packages/pymesos/process.py", line 152, in join
    self.delay_t.join()
      File "/usr/lib/python2.7/threading.py", line 940, in join
    raise RuntimeError("cannot join current thread")
    RuntimeError: cannot join current thread

**Comment by yuyang0** [comment]
it seems that `driver.stop()` should only be invoked in a new thread or the main thread.
